
kind: pipeline
type: docker
name: production

steps:
- name: prepare
  image: busybox
  commands:
    - mkdir -p /cache/${DRONE_REPO}/docker
  volumes:
    - name: cache
      path: /cache
- name: build
  image: plugins/docker:linux-amd64
  settings:
    use_cache: true
    repo: repo.studienprojekt-mathe-lernen.de/wettlauf2              # CHANGE
    registry: repo.studienprojekt-mathe-lernen.de
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest
  volumes:
    - name: docker
      path: /var/lib/docker
    - name: docker-sock
      path: /var/run/docker.sock
- name: update-compose
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    username:
      from_secret: ssh_user
    key:
      from_secret: ssh_key
    target: /opt/wettlauf2                                           # CHANGE
    source: docker-compose.yml
- name: deploy
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: ssh_host
    username:
      from_secret: ssh_user
    key:
      from_secret: ssh_key
    script:
      - cd /opt/wettlauf2                                            # CHANGE
      - docker compose pull -q
      - docker compose up -d

volumes:
  - name: cache
    host:
      path: /var/cache
  - name: docker
    host:
      path: /var/cache/${DRONE_REPO}/docker
  - name: docker-sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push
